# dataset
#custom config trial
dataset: "sky_img"

data_path: "/projects/SkyGAN/webcams/chmi.cz/sky_webcams" # Path to the chmi sky_webcam data
pretrained_model_path: "./pretrained/tvdm/" # Please download pre-trained models from https://huggingface.co/maxin-cn/Latte/tree/main

# save and load
results_dir: "./results_img"
pretrained: "./checkpoints/skytimelapse.pt" # Pretrained model checkpoint from the Latte

# model config: 
model: tvdm-XL/2
num_frames: 16
image_size: 256 # choices=[256, 512]
num_sampling_steps: 250
frame_interval: 3
fixed_spatial: False
attention_bias: True
learn_sigma: True
extras: 1 # [1, 2] 1 unconditional generation, 2 class-conditional generation

# train config:
save_ceph: True # important
use_image_num: 8 # important
learning_rate: 5e-5 # important
ckpt_every: 10000
clip_max_norm: 0.1
start_clip_iter: 20000
local_batch_size: 1 # important
max_train_steps: 1000000 
global_seed: 3407
num_workers: 8
log_every: 50
lr_warmup_steps: 0
resume_from_checkpoint:  # Resume from checkpoint
gradient_accumulation_steps: 4 # TODO
num_classes: 1

# low VRAM and speed up training
use_compile: False
mixed_precision: False
attention_mode: math
enable_xformers_memory_efficient_attention: False
gradient_checkpointing: False


